batch_size: 2
data_folder_name: train_data
early_stopping: -1
epochs: 1000
factor: 0.1
gamma: 0.6666666666666666
input_channels: 3
input_size: 256
lr: 0.001
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: TeethNet
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
